site_name: DHIS2 Documentation Support
site_author: DHIS2 Team
site_url: https://dhis2.github.io/dhis2-doc-support/
copyright: Copyright &copy;2020 DHIS2 Team
site_description: Support for DHIS2 Documentation
repo_url: https://github.com/dhis2/dhis2-doc-support/
edit_uri: blob/master/docs/
use_directory_urls: false

# Configuration
theme:
    name: material
    logo: 'en/resources/images/logo.svg'
    favicon: 'en/resources/images/favicon.ico'
    feature:
      tabs: true
    palette:
      primary: 'white'
      accent: 'blue'

# our css
extra_css:
    - en/resources/css/mkdocs_dhis2.css

 # Extras
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dhis2
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dhis2
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/dhis2 

#plugins
plugins:
    - search
    - git-revision-date-localized
    - awesome-pages 

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - attr_list
    - def_list
    - footnotes
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tabbed
    - pymdownx.tilde

# Navigation
nav:
  - Guidelines: 'index.md'
  - Suggested workflow: 'en/workflow-dhis2-doc.md'
  - Building your documentation: 'en/Building your documentation.md'
